# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 610)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color:black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-30, 0, 891, 101))
        self.frame.setAutoFillBackground(False)
        self.frame.setStyleSheet("background-color: #101010;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(670, 69, 51, 21))
        self.label.setStyleSheet("color: white")
        self.label.setObjectName("label")
        self.logout_btn = QtWidgets.QPushButton(self.frame)
        self.logout_btn.setGeometry(QtCore.QRect(660, 20, 71, 51))
        self.logout_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("exit (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_btn.setIcon(icon)
        self.logout_btn.setIconSize(QtCore.QSize(40, 40))
        self.logout_btn.setObjectName("logout_btn")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(44, 12, 101, 81))
        self.pushButton.setStyleSheet("border: none")
        self.pushButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("My Post (3).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(150, 200))
        self.pushButton.setObjectName("pushButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 100, 101, 491))
        self.widget.setStyleSheet("background-color: #101010;")
        self.widget.setObjectName("widget")
        self.dircam_btn = QtWidgets.QPushButton(self.widget)
        self.dircam_btn.setGeometry(QtCore.QRect(20, 20, 61, 71))
        self.dircam_btn.setStyleSheet("border: none;")
        self.dircam_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("image (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dircam_btn.setIcon(icon2)
        self.dircam_btn.setIconSize(QtCore.QSize(40, 40))
        self.dircam_btn.setObjectName("dircam_btn")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.webcam_btn = QtWidgets.QPushButton(self.widget)
        self.webcam_btn.setGeometry(QtCore.QRect(20, 150, 61, 51))
        self.webcam_btn.setStyleSheet("border: none")
        self.webcam_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("photo-camera (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.webcam_btn.setIcon(icon3)
        self.webcam_btn.setIconSize(QtCore.QSize(40, 40))
        self.webcam_btn.setObjectName("webcam_btn")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 199, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.report_btn = QtWidgets.QPushButton(self.widget)
        self.report_btn.setGeometry(QtCore.QRect(20, 250, 71, 81))
        self.report_btn.setStyleSheet("border: none\n"
"")
        self.report_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("file.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.report_btn.setIcon(icon4)
        self.report_btn.setIconSize(QtCore.QSize(48, 48))
        self.report_btn.setObjectName("report_btn")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(20, 320, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white")
        self.label_5.setObjectName("label_5")
        self.video_btn = QtWidgets.QPushButton(self.widget)
        self.video_btn.setGeometry(QtCore.QRect(20, 370, 61, 81))
        self.video_btn.setStyleSheet("border:none")
        self.video_btn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.video_btn.setIcon(icon5)
        self.video_btn.setIconSize(QtCore.QSize(48, 48))
        self.video_btn.setObjectName("video_btn")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(20, 440, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white")
        self.label_6.setObjectName("label_6")
        self.imgLabel = QtWidgets.QLabel(self.centralwidget)
        self.imgLabel.setGeometry(QtCore.QRect(120, 120, 571, 471))
        self.imgLabel.setStyleSheet("background-color: #181818;\n"
"")
        self.imgLabel.setText("")
        self.imgLabel.setObjectName("imgLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionOpen_file = QtWidgets.QAction(MainWindow)
        self.actionOpen_file.setObjectName("actionOpen_file")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Log Out"))
        self.label_2.setText(_translate("MainWindow", "Gallery"))
        self.label_3.setText(_translate("MainWindow", "Open Webcam"))
        self.label_5.setText(_translate("MainWindow", "View Report"))
        self.label_6.setText(_translate("MainWindow", "View Video"))
        self.actionOpen_file.setText(_translate("MainWindow", "Open file"))
        self.actionClose.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

